import type { BomItem, CircuitBlock } from "@/types/project";
import type { BundleEntry } from "./bundle";

/**
 * Detect the MCU family from a BOM by scanning part names for well-known
 * identifiers. Returns the first match in BOM order (so the engineer's
 * primary MCU choice wins over co-processors).
 *
 * Patterns mirror DR-PROGRAMMING-HEADER (lib/ai/design-rules.ts) so the
 * two stay consistent — if a rule flags a missing programming interface,
 * the firmware scaffolder also detects that MCU.
 *
 * Add families here and in FAMILY_TEMPLATES below.
 */
export type McuFamily = "esp32" | "esp8266" | "stm32" | "rp2040" | "atmega";

// Patterns are "word-start only" — trailing \b is wrong because part
// names like STM32G071 or ESP32-S3 have alphanumerics after the family
// identifier (no word boundary between "32" and "G"). Matching the prefix
// is sufficient.
const FAMILY_PATTERNS: Array<[McuFamily, RegExp]> = [
  ["esp32", /\besp32/i],
  ["esp8266", /\besp8266/i],
  ["rp2040", /\brp2040/i],
  ["stm32", /\bstm32/i],
  ["atmega", /\batmega/i]
];

export function detectMcuFamily(bom: BomItem[]): McuFamily | null {
  for (const item of bom) {
    for (const [family, regex] of FAMILY_PATTERNS) {
      if (regex.test(item.name)) return family;
    }
  }
  return null;
}

// ─── Template helpers ──────────────────────────────────────────────────

/**
 * Architecture blocks that represent a pin connection on the MCU side
 * (sensor inputs, external interfaces). Power and protection blocks
 * aren't GPIO pins, so they're excluded from the scaffold.
 */
function pinBlocks(blocks: CircuitBlock[]): CircuitBlock[] {
  return blocks.filter((b) => b.kind === "sensor" || b.kind === "interface");
}

function pinMacro(blockId: string): string {
  return `PIN_${blockId.toUpperCase().replace(/[^A-Z0-9]+/g, "_")}`;
}

/**
 * Sanitize a user-controlled label before it flows into generated C/C++
 * or .ino source as a comment. Attacker-supplied labels can otherwise
 * inject newlines + #include directives, or break out of block comments
 * via `*` + `/` terminators. We strip newlines, control chars, and any
 * sequence that could close or escape a line comment.
 */
function safeLabelForC(label: string): string {
  return label
    .replace(/[\r\n\x00-\x1f\x7f]/g, " ")
    .replace(/\*\//g, "* /") // defuse block-comment terminator (defence-in-depth)
    .slice(0, 120);
}

/**
 * Emit `pinMode(PIN_FOO, INPUT);` lines for each sensor/interface block.
 * When there are no pin blocks, emit an explanatory comment so the source
 * still compiles and documents the intent.
 */
function renderPinModes(blocks: CircuitBlock[], leadingIndent = "  "): string {
  const pins = pinBlocks(blocks);
  if (pins.length === 0) {
    return `${leadingIndent}// No sensor/interface blocks detected — nothing to configure.\n${leadingIndent}// TODO: configure pins once the hardware is known.`;
  }
  const lines = pins.map((b) => {
    const mode = b.kind === "sensor" ? "INPUT" : "OUTPUT";
    return `${leadingIndent}pinMode(${pinMacro(b.id)}, ${mode}); // ${safeLabelForC(b.label)} (${b.kind})`;
  });
  return lines.join("\n");
}

function renderPinMacros(blocks: CircuitBlock[]): string {
  const pins = pinBlocks(blocks);
  if (pins.length === 0) return "";
  return pins
    .map(
      (b, i) =>
        `#define ${pinMacro(b.id)}  ${i + 2}  // ${safeLabelForC(b.label)} — placeholder, assign real pin`
    )
    .join("\n");
}

// ─── Family templates ──────────────────────────────────────────────────

function platformioIni(platform: string, board: string, framework = "arduino"): string {
  return `; Auto-generated by flux.ai firmware scaffolder. Edit freely.
[env:${board}]
platform = ${platform}
board = ${board}
framework = ${framework}
monitor_speed = 115200
`;
}

function mainCpp(family: McuFamily, blocks: CircuitBlock[]): string {
  const header =
    family === "esp32" || family === "esp8266"
      ? `#include <Arduino.h>\n\n// ${family.toUpperCase()} firmware scaffold generated by flux.ai.\n// Pin numbers below are PLACEHOLDERS — replace with real GPIO assignments.\n`
      : family === "rp2040"
      ? `#include <Arduino.h>\n\n// RP2040 firmware scaffold generated by flux.ai.\n// Pin numbers below are PLACEHOLDERS — replace with real GPIO assignments.\n`
      : `#include <Arduino.h>\n\n// ${family.toUpperCase()} firmware scaffold generated by flux.ai.\n// Pin numbers below are PLACEHOLDERS — replace with real GPIO assignments.\n`;

  const macros = renderPinMacros(blocks);
  return `${header}
${macros}

void setup() {
  Serial.begin(115200);
  Serial.println("flux.ai scaffold starting...");
${renderPinModes(blocks)}
}

void loop() {
  // TODO: implement the main control loop.
  delay(1000);
}
`;
}

function firmwareIno(blocks: CircuitBlock[]): string {
  const macros = renderPinMacros(blocks);
  return `// ATmega firmware scaffold generated by flux.ai.
// Pin numbers below are PLACEHOLDERS — replace with real pins from your schematic.

${macros}

void setup() {
  Serial.begin(9600);
${renderPinModes(blocks)}
}

void loop() {
  // TODO: implement the main control loop.
  delay(1000);
}
`;
}

function readme(family: McuFamily, board: string, isPlatformIO: boolean): string {
  const build = isPlatformIO
    ? `## Build\n\n\`\`\`\npio run\npio run -t upload\npio device monitor\n\`\`\`\n\nRequires [PlatformIO](https://platformio.org/) installed (\`pip install platformio\`).`
    : `## Build\n\nOpen \`firmware.ino\` in the Arduino IDE, select the matching board and port, click Upload.`;

  return `# Firmware scaffold — ${family.toUpperCase()}

This folder contains a minimal, buildable firmware project matched to the ${family.toUpperCase()} MCU detected in your BOM (${board}).

## What's here

- \`${isPlatformIO ? "platformio.ini" : "firmware.ino"}\` — project config${isPlatformIO ? "\n- `src/main.cpp` — entry point with setup() and loop()" : ""}
- Pin macros (\`PIN_*\`) generated from your architecture's sensor / interface blocks

## Important: pin numbers are placeholders

flux.ai does not know the physical pinout of the ${family.toUpperCase()} you selected — the \`#define PIN_XYZ  N\` lines assign arbitrary sequential numbers. **Open your schematic in KiCad, identify which GPIO each block connects to, and update the pin macros before flashing.**

${build}

## What's generated

- setup() initialises Serial at 115200 and calls \`pinMode\` for every sensor and interface block in the architecture
- loop() is intentionally empty — add your control logic here

Happy hacking!
`;
}

// ─── Public API ────────────────────────────────────────────────────────

interface FamilyPlatformIOConfig {
  platform: string;
  board: string;
  framework?: string;
}

const FAMILY_PIO: Record<Exclude<McuFamily, "atmega">, FamilyPlatformIOConfig> = {
  esp32: { platform: "espressif32", board: "esp32dev" },
  esp8266: { platform: "espressif8266", board: "nodemcuv2" },
  stm32: { platform: "ststm32", board: "genericSTM32F103C8" },
  rp2040: { platform: "raspberrypi", board: "pico" }
};

/**
 * Generate the firmware/ folder entries to append to the KiCad export
 * bundle. Returns [] when no MCU is detected — graceful no-op rather
 * than error, so passive-only designs still export cleanly.
 */
export function generateFirmwareEntries(
  bom: BomItem[],
  blocks: CircuitBlock[]
): BundleEntry[] {
  const family = detectMcuFamily(bom);
  if (!family) return [];

  if (family === "atmega") {
    return [
      { name: "firmware/firmware.ino", content: firmwareIno(blocks) },
      { name: "firmware/README.md", content: readme(family, "ATmega328P", false) }
    ];
  }

  const cfg = FAMILY_PIO[family];
  return [
    { name: "firmware/platformio.ini", content: platformioIni(cfg.platform, cfg.board, cfg.framework) },
    { name: "firmware/src/main.cpp", content: mainCpp(family, blocks) },
    { name: "firmware/README.md", content: readme(family, cfg.board, true) }
  ];
}
